### PR TITLE
New widgets: TabHeader, TabWidget, StackedWidget

### PR DESCRIPTION
**Pull request by Thorius94**

### CODE REVIEW

**Comment by wjakob** [comment]
(never mind the Python errors on the CI build bot, I can fix those later on)

**Comment by wjakob** [comment]
Let me know when this is ready to merge.

**Comment by Thorius94** [comment]
Besides the Python errors, everything else seems to be in order. I think it should be ready now.

**Comment by wjakob** [comment]
Ok, thank you! I'll merge this on the weekend or on Monday at the latest.

**Pull request closed without merging**
