### PR TITLE
Adding check for null Screen which was causing a crash in our project.

### PR DESCRIPTION
**Pull request by nhojb**

### CODE REVIEW

**Comment by wjakob** [comment]
Actually, I committed this perhaps a bit prematurely -- do you have any intuition why  ``Screen*`` might be ``nullptr``? It does not appear to be a normal situation in a NanoGUI program.

**Comment by nhojb** [comment]
Not sure. Our use of nanogui is probably unusual in that we use it as part of a plugin for Final Cut Pro X. As such we are creating and tearing down the nanogui stack in response to user actions. It's possible that the invalid state is the cause of this.

Having said that we were encountering this crash frequently and this change did fix the issue. However it may be particular to our usage.

**Comment by wjakob** [comment]
ok, that seems fine given that it is such a tiny change.

**Comment by wjakob** [comment]
Out of curiosity, what's the name of your plugin?

**Comment by nhojb** [comment]
ColorFinale: http://try.colorgradingcentral.com/colorfinale/

We use nanogui for our on-screen-controls. I've been very impressed with the architecture (Qt inspired?) and the quality of the code ;-)

**Pull request merged**
