### PR TITLE
Enable coroutine support on every platform

### PR DESCRIPTION
**Pull request by mrzv**

### CODE REVIEW

**Comment by wjakob** [comment]
A comment: let's enable coroutines on Mac and Linux, but not on Windows.

**Comment by wjakob** [comment]
Processing events on a different thread there is fine AFAIK.

**Comment by wjakob** [comment]
(I think I actually tested your example3 at some point)

**Comment by mrzv** [comment]
How do you check for Linux in your code?

**Comment by wjakob** [comment]
```
#if defined(__linux__)
...
#endif
```

**Comment by mrzv** [comment]
Ok, I think I got it now.

**Comment by wjakob** [comment]
thanks!

**Pull request merged**
