### PR TITLE
Aux drawing function

### PR DESCRIPTION
**Pull request by fairlight1337**
This removes the need to call `Widget::draw()` from `Widget` subclasses by adding an auxiliary drawing function that does the housekeeping for drawing.

I tried to adhere to your coding style as closely as possible.

### CODE REVIEW

**Comment by wjakob** [comment]
Hi @fairlight1337 ,

can you motivate this patch a bit? It wasn't immediately obvious to me why you made this change.

Thanks,
Wenzel

**Comment by fairlight1337** [comment]
Hey Wenzel,

Sure, I'll try. Reading the guidelines of what nanogui wants to achieve, I assumed that using less code in subclasses makes it more accessible for contributors. Also (as I keep forgetting these things easily myself) remembering to draw the superclass's overridden function can result in weird bugs that are not always easy to trace.

That was my main motivation. Or is this making the drawing code too complicated?

Jan

**Comment by wjakob** [comment]
Hi,

thanks for the explanation. In this case, I think I'd prefer the old behavior. Although your patch simplifies the default implementation of widgets, it adds some API complexity by being different from how the drawing logic is implemented in other libraries (e.g. Qt, Java/Swing).

Best,
Wenzel

**Comment by fairlight1337** [comment]
Hi,

Thanks for the remarks. I see that point, you're probably right that the API complexity outweighs the gains in widget simplicity.

Cheers,
Jan

**Pull request closed without merging**
