### PR TITLE
Add a new Dial widget based on the knob of the Slider widget

### PR DESCRIPTION
**Pull request by ermarch**
This adds a new Dial widget which is visually based on the knob of the Slider widget.
Mouse dragging is supported as well as mouse clicking.
dial

### CODE REVIEW

**Comment by wjakob** [comment]
huh?

**Comment by ermarch** [comment]
On 5/17/19 3:16 PM, Wenzel Jakob wrote:
> huh?


Hi Wenzel,

I assume you refer to the fact that the pull request was closed?

It's because I fount the Contributing section on the website and decided 
to follow the rules laid out there (GitHub is very new to me).

Do you want me to re-open the pull request?

I've another one pending about the option to specify whether the 
imageViewer should display borders or not.

Regards,

Erik Hofman

**Comment by wjakob** [comment]
Hi Erik,
I was indeed wondering why you started on a nice-looking feature and then closed the PR. I'm pretty busy these days but can take a look in the next weeks (either here or in another PR, as you prefer).
Best,
Wenzel

**Comment by ermarch** [comment]
On 5/17/19 3:42 PM, Wenzel Jakob wrote:
> Hi Erik,
> I was indeed wondering why you started on a nice-looking feature and 
> then closed the PR. I'm pretty busy these days but can take a look in 
> the next weeks (either here or in another PR, as you prefer).

Alright, I'll create a new pull request for both features.

Erik

**Pull request closed without merging**
