### PR TITLE
[docs] fixing link_title so templates do not have name trimmed

### PR DESCRIPTION
**Pull request by svenevs**
Hey @wjakob I actually got lucky, not much had to change for things to work...I think.

I don't know if you've looked at the docs recently, but something has gone terribly wrong lately.  I posted [an issue](https://github.com/michaeljones/breathe/issues/303) on breathe's page, but titles for almost everything are getting deleted.

I see two possible options:

1. Hard-code a specific (earlier) version of breathe in `requirements.txt`
2. Try and use [this stuff](https://github.com/arximboldi/immer/commit/e6e3c3f7d8ed4ade23928c3db56ca90108d02b85).  I haven't tested this, and it is definitely not going to fix everything for us here.

I made this a PR to start a discussion, but this should not be merged in as is.

### CODE REVIEW

**Comment by svenevs** [comment]
OKEJ!  Breathe v4.2.0 seems to be what we want here, though I don't understand why that failed the AppVeyor test.

| Your Docs | Fake Docs |
| [cursor](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_enum_nanogui__Cursor.html) | [cursor](http://fake-nanogui.readthedocs.io/en/latest/generated_api/exhale_enum_nanogui__Cursor.html#enum-nanogui-Cursor) |
| [textbox](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_class_nanogui__TextBox.html#class-nanogui-TextBox) | [textbox](http://fake-nanogui.readthedocs.io/en/latest/generated_api/exhale_class_nanogui__TextBox.html#class-nanogui-TextBox) |
| [arcball](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_struct_nanogui__Arcball.html) | [arcball](http://fake-nanogui.readthedocs.io/en/latest/generated_api/exhale_struct_nanogui__Arcball.html) |

For reference, `serialization_traits` described above are [here].  So for us, we can just use 4.2.0 via requirements.txt.

Followup: do you actually still need the `namespace half_float` in `serializer/core.h` still?  That's the only one skipped right now, the issue being that if you want the template specialization to show up in the right place the namespace / class have to be documented.  Currently the doxygen preprocessor is skipping that at the beginning, and kind of freaks out when it hits the specialization.  The result is it somehow ends up in the global namespace.

Followup 2: of what remains in `serializer/core.h`, is there anything you **do not** want documented?  The code is uh...confusing.  So docs for it are great.  But I'm at a loss of what to even write down.  Would you be willing to give a fly-by-night explanation of how `Serializer`, `serialization_helper`, and `serialization_traits` actually end up working with one another?

**Comment by svenevs** [comment]
Just remembered this PR from the emails about adding docs to README, Breathe updated to 4.5.0 and I think they fixed the sphinx 1.5.1 compatibility problems, so this shouldn't be needed anymore!

**Comment by wjakob** [comment]
Hey @svenevs,

really sorry about the lack of a response. This was right during the siggraph crunch and just got buried in my email. 

Wenzel

**Comment by svenevs** [comment]
No problem, I know the game.  The lab here was full of zombies...Anyway the original intent for the PR was for templates, but assuming docs actually get added i'm pretty sure exhale supports them (at least for my frameworks it does).

Submitting a different PR now with updated exhale (minor bugfix).

**Pull request closed without merging**
