### PR TITLE
[docs] Initial documentation.

### PR DESCRIPTION
**Pull request by svenevs**
This commit enables hosting of the documentation on RTD.  Steps to incorporate:

1. Create a 'NanoGUI' project on RTD.
2. Setup commit hooks (should be done already since you are hosting pybind11 there).
3. Go to the admin page of your RTD project site, select the *Advanced Settings* tab.
   - Make sure 'Install your project inside a virtualenv using setup.py install' is checked
   - Set the 'Requirements file' just below this to ``docs/requirements.txt``

Assuming you call the RTD project just 'NanoGUI', it should give you the URL 'nanogui.rtfd.io'.

The current build of this commit is viewable here: fake-nanogui.rtfd.io

Notes:

- This was a rather large commit, as well as merge.  Oversight may be beneficial.
- Known python documentation bindings issues: ComboBox and GridLayout::set{Col,Row}Alignment_2
    - clang doesn't produces strings for these
    - ComboBox unexplainable
    - GridLayout function signature may be getting unboxed magically, resolving to the
      original declarations with parameter Alignment.  Unsure if there is a fix.
- docs/contributing.rst
    - Too verbose.  Did not know how much or little documentation to include on how to
      document the code.
- docs/examples.rst
    - Better descriptions of all would be more helpful, right now they basically just say
      "go look at the code".
- docs/usage.rst
    - Better explanation of differences between C++ and Python API

Misc:

- Documentation builds after each commit.  The entire API is re-generated via conf.py's
  setup(app) method.
    - To change the verbiage at the top of the 'Library API' page, modify the variable
      'libraryDescription' at the bottom of conf.py (before call to generate).
- Clickable hierarchies are awkward on mobile devices.  Functional, but frustrating.

### CODE REVIEW

**Comment by svenevs** [comment]
Ugh.  RTD has done it again.  Functions and their respective files are not linked to each other online, but link properly with local builds.  This is likely related to ``NANOGUI_EXPORT`` / the Doxygen strip from path settings.  I had to do some arguably dubious manual stripping for RTD in ``exhale.py``...

In order to investigate this further though, I will need to make public commits to see how RTD handles.  Should I wait until this is reviewed / merged?  The function documentation still appears in the full api listing, just not on the File pages / function pages do not link to their defining file.

**Comment by wjakob** [comment]
Perfect -- let's merge this first (I've also pushed a follow-up commit with a few very minor changes to your PR.). Thank you again very much for the very nice job 👍 

Could you please take a look at the remaining RTD issue you mentioned and resolve via a separate PR? It's no problem to do a few iterations if needed.

**Comment by wjakob** [comment]
Hi Stephen,

super-stupid question: yesterday I wanted to locally generate the documentation on my machine instead of pushing & letting RTD do the job, but I didn't know how to do it with the current setup.

Following the usual "make mkdoc" command, could you let me know which commands to run to start the breathe/exhale/sphinx pipeline?

Best,
Wenzel

**Comment by svenevs** [comment]
Lol. It's not exactly a translucent process... Not at a computer right now (can give better instructions later), but the html and Python docs come from two different makefiles.

Html from `docs/Makefile`, with `make html` starting the chain locally. If memory serves me it creates `_build/html/index.html` to view locally.

The pydoc stuff comes from the makefile generated by `cmake`

**Comment by wjakob** [comment]
Aha! Is it possible that the ``Makefile`` was never checked in? I don't seem to have it here.

The ``pydoc`` part is clear to me.

**Comment by svenevs** [comment]
Eeek sorry!!! Apparently only the windows version. I can regenerate one when I'm back on campus. Honestly it's kind of mysterious that RTD is building, pretty sure they're Unix sandboxes. Maybe they run Sphinx build manually?

ETA 10am EST or so, sorry again x0

**Comment by svenevs** [comment]
Hehehe so it turns out I wasn't paying very close attention, the `.gitignore` was (righteously) ignoring `Makefile`...

I made a new PR with the `Makefile` from `sphinx-quickstart`, I ran it locally and everything built for me.  Did you want me to put [this section](http://nanogui.readthedocs.io/en/latest/compilation.html#compiling-the-documentation) on its own with notes on how to handle the `py_doc` stuff?  Shouldn't be too much effort, it might be helpful (from the awesome GLCanvas thread) to be a little more specific about how the docs actually work, with details on how to at the very least not break the python docs ;)

**Comment by wjakob** [comment]
(I think it's clear enough how it is. I actually didn't realize that there was documentation on the documentation, so I never checked ;))

**Pull request merged**
